apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  release_name: {{ .Release.Name }}
  release_service: {{ .Release.Service }}
  chart_name_version: {{ .Chart.Name }}-{{ .Chart.Version }}
  my_number: {{ .Values.my_number | quote }}
  my_name: {{ .Values.my_name | upper }}
  my_age: {{ .Values.my_age | quote }}
